name: SpaceONE Review

on:
  pull_request:
    branches:
      - master
jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set environment virables
      env:
        # LOCATION points the parent directory
        LOCATION_SETUP_PY: src # optional. for pypi upload
      run: |
        echo "LOCATION_SETUP_PY=$LOCATION_SETUP_PY" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build
      run: |
        cd $LOCATION_SETUP_PY
        python setup.py sdist bdist_wheel

    - name: Test
      id: test
      run: |
        echo "Running test ... None"
        # fail test or pass test